# Generated by Django 5.0.6 on 2024-06-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='TwoFactor',
            field=models.BooleanField(db_column='TwoFactor', default=False),
        ),
    ]
